apiVersion: v1
kind: ConfigMap
metadata:
  name: temporal-dynamicconfig
data:
  development-sql.yaml: |
    system.forceSearchAttributesCacheRefreshOnRead:
      - value: true
        constraints: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal
  labels:
    app: temporal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal
  template:
    metadata:
      labels:
        app: temporal
    spec:
      containers:
        - name: temporal
          image: temporalio/auto-setup:1.25
          ports:
            - containerPort: 7233
              name: grpc
            - containerPort: 7243
              name: http
          env:
            - name: DB
              value: postgres12
            - name: DB_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: temporal
            - name: POSTGRES_PWD
              value: temporal
            - name: POSTGRES_SEEDS
              value: postgres
            - name: DYNAMIC_CONFIG_FILE_PATH
              value: /etc/temporal/config/dynamicconfig/development-sql.yaml
          volumeMounts:
            - name: dynamicconfig
              mountPath: /etc/temporal/config/dynamicconfig
          readinessProbe:
            exec:
              command: ['tctl', '--address', '127.0.0.1:7233', 'workflow', 'list']
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command: ['tctl', '--address', '127.0.0.1:7233', 'workflow', 'list']
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
      volumes:
        - name: dynamicconfig
          configMap:
            name: temporal-dynamicconfig
---
apiVersion: v1
kind: Service
metadata:
  name: temporal
spec:
  selector:
    app: temporal
  ports:
    - name: grpc
      port: 7233
      targetPort: 7233
    - name: http
      port: 7243
      targetPort: 7243
